### PR TITLE
WIP Update Ubiquity package

### PR DESCRIPTION
**Pull request by anniephan**
Work in progress. Based from https://github.com/cloudflare/cfssl/wiki/Update-Ubiquity-package.

`format.go`(https://github.com/anniephan/cfssl_trust/blob/ubiquity-update/cmd/format/format.go) takes in a file full of certificates and a directory, to generate separate certificates following a naming convention inside that directory.

The current naming convention of certificates is `commonname_issuedate_sigalg.crt`.

### CODE REVIEW

**Comment by lziest** [comment]
LGTM, later cross-check (sync-up) /temp/ with /intermediate_ca/ directory.

**Comment by anniephan** [comment]
The most recent commit put certificates from `int-bundle.crt` into the `intermediate_ca/` directory. The certificates from `ca-bundle.crt` are put in the `ca-bundle` directory I created.

**Comment by lziest** [comment]
it's also nice to put the format.go to cmd/format/format.go

**Comment by anniephan** [comment]
Alright, yeah that can be arranged.

**Comment by anniephan** [comment]
@lziest Found an issue when using an x509.Certificate object, `certificate.SignatureAlgorithm` returns an int ranging from 0-11 instead of a string of the actual sigalg for our file naming convention `commonname_issuedate_sigalg.crt`.

**Comment by lziest** [comment]
try https://github.com/cloudflare/cfssl/blob/master/helpers/helpers.go#L114

**Comment by anniephan** [comment]
Ah, didn't see that before for some reason. Thanks!

**Comment by lziest** [comment]
lgtm, squash to one commit.

**Comment by anniephan** [comment]
Done.

**Comment by lziest** [comment]
Hmm, can you make the commit message more of a summary? Thanks!

**Pull request merged**
