### PR TITLE
Add schema for future automated certificate bundling.

### PR DESCRIPTION
**Pull request by kisom**
My database skills aren't the greatest, so I could use extra eyes on this to make sure it's the right way forward.

### CODE REVIEW

**Comment by jkroll-cf** [comment]
It seems odd to me to build the schema directly by writing SQL statements, when you could use an abstraction layer like https://godoc.org/github.com/mattes/migrate or Goose (NB - I have experience only with the latter, but it's unmaintained so I can't in good conscience recommend it). Am I missing something?

**Comment by kisom** [comment]
Two things:

* I didn't know this existed, and I knew Goose was unmaintained.
* This approach took 15 minutes.

Keep in mind once the CLI tooling starts to shape up, this generator will likely disappear. It's an easy way right now to test the SQL out.

**Comment by ahrex** [comment]
LGTM. How do I approve?

**Comment by jkroll-cf** [comment]
@kisom That seems reasonable. I was just thinking that using a migration framework would make changes more extensible (e.g., migration frameworks support schema versioning and evolution).

LGTM

**Pull request merged**
